Update old function, remove mobile robot wrapper
stack-of-tasks/pinocchio pull request #1490
Opened 2021-08-11 11:23 UTC by kozakromch

Hello. I try to do this exercise, but noticed that there are a lot of deprecated or not working function. 
class mobileRobotWrapper not working, and I don't know how to fix it, so I remove it.

2021-08-11 16:40 UTC, jcarpent commented
Thanks for the contribution. 
The ambition of having the mobile platform is to solve more complex IK problems as you might have noticed.
What is not working in particular?
@proyan Could you help on this task?

2021-08-12 08:14 UTC, kozakromch commented
Oh. Okay, I get it. In MobileRobot instead of call super.__init__ I should call initFromUrdf. 

But actually I don't know the final result. Is it okay that robot could slide away from mobile platform ?
![image](https://user-images.githubusercontent.com/14368253/129159853-3695d32b-23e4-417a-b9ee-31075327b07f.png)

2021-08-12 11:27 UTC, proyan commented
I'm on holiday today and tomorrow, I'll be able to look at it Monday

2021-08-18 14:39 UTC, proyan commented on doc/d-practical-exercises/3-invkine.md
> +from mobilerobot import MobileRobotWrapper
I thought the purpose of this PR was to remove mobilerobot? :)
Could you instead use robotwrapper here?

2021-08-18 14:39 UTC, proyan commented on doc/d-practical-exercises/3-invkine.md
> +robot.viz.display(q)
just robot.display should be fine, you don't need robot.viz here, or in other places in this PR.

2021-08-18 14:39 UTC, proyan commented on doc/d-practical-exercises/3-invkine.md
> +q = pin.integrate(robot.model, pin.neutral(robot.model), np.random.rand(NV) * 10)
you should use pin.randomConfiguration here, no need to use this trick to handle lie spaces

2021-08-18 14:39 UTC, proyan commented on doc/d-practical-exercises/3-invkine.md
> +    robot.viz.viewer.gui.applyConfiguration(name, pin.SE3ToXYZQUAT(M).tolist())
same here, robot.viewer is directly available, and we don't need viz here

2021-08-23 12:56 UTC, proyan approved these changes

2021-08-23 13:16 UTC, proyan requested changes

2021-08-23 13:16 UTC, proyan commented on doc/d-practical-exercises/3-invkine.md
> +pin.updateFramePlacements(robot.model, robot.data)
```suggestion
pin.framesForwardKinematics(robot.model, robot.data, q)
```

2021-08-23 13:16 UTC, proyan commented on doc/d-practical-exercises/3-invkine.md
> +viewer.gui.addXYZaxis('world/framegoal', [1., 0., 0., 1.], .015, 4)
```suggestion
robot.viewer.gui.addXYZaxis('world/framegoal', [1., 0., 0., 1.], .015, 4)
```

2021-08-23 16:45 UTC, proyan approved these changes

2021-08-23 16:49 UTC, proyan commented
Thanks @kozakromch for the contribution.

2021-08-23 16:49 UTC, merged

2021-08-23 16:49 UTC, jcarpent approved these changes
Thanks @proyan and @kozakromch for handling this PR.