Configuration limits for joints and model
stack-of-tasks/pinocchio pull request #1756
Opened 2022-09-29 12:25 UTC by fabinsch

- every joint returns a vector of boolean of size nq describing if each of the DOF has bounds or not
- model: vector stacking the boolean vector of configurations limits of each joint in the model

now we can do:
```
In [1]: import pinocchio as pin
   ...: model = pin.Model()
   ...: model.addJoint(0, pin.JointModelFreeFlyer(), pin.SE3.Identity(), "root_joint")
   ...: model.addJoint(0, pin.JointModelRZ(), pin.SE3.Identity(), "joint1")
   ...: model.addJoint(0, pin.JointModelRUBZ(), pin.SE3.Identity(), "joint2")
   ...: model.configurationLimit.tolist()
Out[1]: [True, True, True, False, False, False, False, True, False, False]
```

which can be used to see where bounds are expected or not using e.g. `model.upperPositionLimit[model.configurationLimit.tolist()]` and check if these are meaningful joint bounds, as suggested in #1752 .

2022-09-29 13:50 UTC, stephane-caron commented
In the IK joint-limit use case https://github.com/stack-of-tasks/pinocchio/issues/1752#issuecomment-1260773339, what we compute in the end is the same thing but in tangent rather than configuration space; something like:

```python
v_max[np.hstack([joint.has_configuration_limit_in_tangent_space.tolist() for joint in model.joints]))
```

This is beyond the scope of this PR, but I'm not sure I understand why planar (rotation), spherical or free-flyer (rotations) shouldn't have limits. In general, spherical joints can have arbitrary boundaries. For example in HRP-2's hips there was once a polygonal description ``A * [phi, theta] <= b``.

2022-09-29 13:51 UTC, stephane-caron commented on bindings/python/multibody/joint/joint-derived.hpp
> +        .add_property("configuration_limit", &JointModelDerived::hasConfigurationLimit,
Maybe ``"has_configuration_limit"`` so that the API names match (if not their case)?

2022-09-30 13:24 UTC, jcarpent requested changes
I think we need to uniformize the namings.
I made some suggestions. @fabinsch Could you handle the rest?

2022-09-30 13:24 UTC, jcarpent commented on bindings/python/multibody/model.hpp
> +        .add_property("configurationLimit",&Model::configurationLimit)
```suggestion
        .add_property("hasConfigurationLimit",&Model::hasConfigurationLimit)
```

2022-09-30 13:24 UTC, jcarpent commented on bindings/python/multibody/joint/joint.hpp
> +        .def("has_configuration_limit", &JointModel::hasConfigurationLimit,
```suggestion
        .def("hasConfigurationLimit", &JointModel::hasConfigurationLimit,
```

2022-09-30 13:24 UTC, jcarpent commented on bindings/python/multibody/joint/joint-derived.hpp
> +        .add_property("has_configuration_limit", &JointModelDerived::hasConfigurationLimit,
```suggestion
        .add_property("hasConfigurationLimit", &JointModelDerived::hasConfigurationLimit,
```

2022-09-30 14:39 UTC, stephane-caron commented
Hi guys. This is just a proposal. Since there can be joints with partial configuration limits, it would be convenient if Pinocchio also exported a tangent vector, like e.g. for the free flyer:

```cpp
    const std::vector<bool> JointModelFreeFlyerTpl::hasConfigurationLimitTangent() const
    {
      return {true, true, true, false, false, false};
    }
```

Here is the kind of things this tangent vector could be used for:

```python
has_configuration_limit = np.logical_and(  # runtime configuration limit
    model.upperPositionLimit < 1e20,
    model.upperPositionLimit > model.lowerPositionLimit + 1e-10,
)

bounded_joints = [
    joint
    for joint in model.joints
    if has_configuration_limit[
        # this slice could be partial thanks to hasConfigurationLimit
        slice(joint.idx_q, joint.idx_q + joint.nq)
    ].all()
]

is_tangent_of_bounded_joint = np.full(model.nv, False)
for joint in bounded_joints:
    is_tangent_of_bounded_joint[
        # this slice could be partial with hasConfigurationLimitTangent
        slice(joint.idx_v, joint.idx_v + joint.nv)
    ] = True
```

Alternatively, if we had a map from configuration to tangent coordinates https://github.com/stack-of-tasks/pinocchio/issues/1758, we could forget about ``hasConfigurationLimitTangent`` and simply do:

```python
is_velocity_of_bounded_joint = np.full(model.nv, False)
for i in range(model.nq):
    if has_configuration_limit[i]:
        is_velocity_of_bounded_joint[model.config_to_tangent(i)] = True
```

2022-10-04 20:55 UTC, jcarpent approved these changes
Thanks @fabinsch for this nice work.

2022-10-05 13:41 UTC, merged