Changed Geometry Objects bindings and added getMotionAxis function
stack-of-tasks/pinocchio pull request #2315
Opened 2024-07-08 13:39 UTC by MegMll

As discussed in https://github.com/stack-of-tasks/pinocchio/issues/2258, this pr changed the way the geometry material is parsed using eigenpy variant. 

It also adds a function to have an easy access to the joint axis for prismatic, revolute and helicoidal joints. https://github.com/stack-of-tasks/pinocchio/discussions/2196

2024-07-09 09:38 UTC, jorisv requested changes
Apply the same change on prismatic, revolute unbounded and revolute

2024-07-09 09:42 UTC, jorisv commented
Add the following changelog entry in the added section:

- Add getMotionAxis method to helical, prismatic, revolute and ubounded revolute joint.

In changed section:

- Use eigenpy to expose `GeometryObject::meshMaterial` variant

2024-07-09 12:06 UTC, jorisv submitted a review, later dismissed

2024-07-09 12:28 UTC, jcarpent requested changes
I propose this change and fix for the Python doc.

2024-07-09 12:28 UTC, jcarpent commented on include/pinocchio/bindings/python/multibody/joint/joints-models.hpp
> +      return cl.def(bp::init<>(bp::args("self"), "Init JointModelRX with x as rotation axis"))
```suggestion
      return cl.def(bp::init<>(bp::args("self"), "Init JointModelRX with the X axis as rotation axis ([1,0,0])."))
```

2024-07-09 12:28 UTC, jcarpent commented on include/pinocchio/bindings/python/multibody/joint/joints-models.hpp
> +      return cl.def(bp::init<>(bp::args("self"), "Init JointModelRY with y as rotation axis"))
```suggestion
      return cl.def(bp::init<>(bp::args("self"), "Init JointModelRY with the Y axis as rotation axis ([0,1,0])."))
```

2024-07-09 12:28 UTC, jcarpent commented on include/pinocchio/bindings/python/multibody/joint/joints-models.hpp
> +      return cl.def(bp::init<>(bp::args("self"), "Init JointModelRZ with z as rotation axis"))
```suggestion
      return cl.def(bp::init<>(bp::args("self"), "Init JointModelRZ with the Z axis as rotation axis ([0,0,1])."))
```

2024-07-09 12:28 UTC, jcarpent commented on include/pinocchio/bindings/python/multibody/joint/joints-models.hpp
> +      return cl.def(bp::init<>(bp::args("self"), "Init JointModelRUBX with x as rotation axis"))
```suggestion
      return cl.def(bp::init<>(bp::args("self"), "Init JointModelRUBX with the X axis as rotation axis ([1,0,0])."))
```

2024-07-09 12:28 UTC, jcarpent commented on include/pinocchio/bindings/python/multibody/joint/joints-models.hpp
> +      return cl.def(bp::init<>(bp::args("self"), "Init JointModelRUBY with y as rotation axis"))
```suggestion
      return cl.def(bp::init<>(bp::args("self"), "Init JointModelRUBY with the Y axis as rotation axis ([0,1,0])."))
```

2024-07-09 12:28 UTC, jcarpent commented on include/pinocchio/bindings/python/multibody/joint/joints-models.hpp
> +      return cl.def(bp::init<>(bp::args("self"), "Init JointModelRUBZ with z as rotation axis"))
```suggestion
      return cl.def(bp::init<>(bp::args("self"), "Init JointModelRUBZ with the Z axis as rotation axis ([0,0,1])."))
```

2024-07-09 12:28 UTC, jcarpent commented on include/pinocchio/bindings/python/multibody/joint/joints-models.hpp
> +      return cl.def(bp::init<>(bp::args("self"), "Init JointModelPX with x as rotation axis"))
```suggestion
      return cl.def(bp::init<>(bp::args("self"), "Init JointModelPX with the X axis as translation axis ([1,0,0])."))
```

2024-07-09 12:28 UTC, jcarpent commented on include/pinocchio/bindings/python/multibody/joint/joints-models.hpp
> +      return cl.def(bp::init<>(bp::args("self"), "Init JointModelPY with y as rotation axis"))
```suggestion
      return cl.def(bp::init<>(bp::args("self"), "Init JointModelPY with the Y axis as translation axis ([0,1,0])."))
```

2024-07-09 12:28 UTC, jcarpent commented on include/pinocchio/bindings/python/multibody/joint/joints-models.hpp
> +      return cl.def(bp::init<>(bp::args("self"), "Init JointModelPZ with z as rotation axis"))
```suggestion
      return cl.def(bp::init<>(bp::args("self"), "Init JointModelPZ with the Z axis as translation axis ([0,0,1])."))
```

2024-07-10 07:28 UTC, jorisv approved these changes

2024-07-10 07:28 UTC, merged

2024-12-17 18:24 UTC, joao-pm-santos96 commented
is getMotionAxis accessible though python?

2024-12-18 08:35 UTC, jorisv commented
Hello @joao-pm-santos96,

Yes, it's you can access it from Python.
But you have to extract the underlying joint from the JointModel to have access to this method.

```python
import pinocchio as pin

model = pin.Model()
j1 = pin.JointModelRX()
print(j1.getMotionAxis())
model.addJoint(0, j1, pin.SE3.Identity(), "j1")

j1_model = model.joints[0]
# Don't work
# print(j1_model.getMotionAxis())
# Work
print(j1_model.extract().getMotionAxis())
```

2024-12-18 08:57 UTC, joao-pm-santos96 commented
> Hello @joao-pm-santos96,
> 
> Yes, it's you can access it from Python. But you have to extract the underlying joint from the JointModel to have access to this method.
> 
> ```python
> import pinocchio as pin
> 
> model = pin.Model()
> j1 = pin.JointModelRX()
> print(j1.getMotionAxis())
> model.addJoint(0, j1, pin.SE3.Identity(), "j1")
> 
> j1_model = model.joints[0]
> # Don't work
> # print(j1_model.getMotionAxis())
> # Work
> print(j1_model.extract().getMotionAxis())
> ```

Worked perfectly! Thank you once again! 😄