Separate collision_color in MeshcatVisualizer.loadViewerModel
stack-of-tasks/pinocchio pull request #2350
Opened 2024-07-25 13:24 UTC by stephane-caron

The proposal of this PR is to add a separate ``collision_color`` argument to `MeshcatVisualizer.loadViewerModel`.

- **Before:** `color` applies to both visual and collision model
- **After:** `color` applies to visual, `collision_color` to collision model

This can be convenient to debug collision meshes alongside the visual model (with only `color`, meshes overlapped):

```py
robot.setVisualizer(MeshcatVisualizer())
robot.initViewer(open=True)
robot.loadViewerModel(collision_color=(1.0, 0.0, 0.0, 0.3))
robot.viz.displayCollisions(True)
```

![image](https://github.com/user-attachments/assets/ce227a29-6c0d-448c-82a0-f4bb841717fe)

2024-07-25 14:53 UTC, jcarpent commented
@stephane-caron could you rebase instead of merging ?

2024-07-25 14:54 UTC, stephane-caron commented
> @stephane-caron could you rebase instead of merging ?

Sure. GitHub gave me a button to resolve the conflict and I naively clicked on it :blush:

2024-07-25 17:11 UTC, jcarpent requested changes
I would go for `visual_color` too. And when color is there, it should be used for both, or mark it as deprecated option.

2024-07-27 07:07 UTC, jcarpent approved these changes

2024-07-27 08:27 UTC, merged