Extend Support for Mimic Joint
stack-of-tasks/pinocchio pull request #2441
Opened 2024-09-30 14:41 UTC by MegMll

## Overview
This PR enhances support for the mimic joint.
Mimic joint refer to a joint which configuration depends on the configuration of another joint (that we named the primary joint). The relation is $q_{mimic} = \alpha * q_{primary} + \beta$ (where $\alpha, \beta$ are defined by the user)

## Key Updates:
#### URDF Parsing:

The mimic tag can now be parsed from urdf, and add the corresponding mimic joint to the model.
A `mimic` flag has been added to the parser to enable this feature or not (default to `false`) in order to preserve backward compatibility.

#### Robot and Joint Model Modifications:

* The already existing mimic joint type has been update to allow support in more algorithms.
    * The main change being that instead of being templated on the primary joint type, the mimic joint now holds a variant of joint for the primary.
* The robot and joint `nq` and `nv` (resp. `idx_q`, `idx_v`) values have now been extended with a `nj` (resp `idx_j`) value, holding the dimension of the extended robot/joint tangeant space. (for all classical joint `nv==nj` but for mimic `nv==0` and `nj==primary.nj`). The suffix j stand for Jacobian as those values are mainly used for computing jacobians rows and columns.

#### Algorithms:

* The following algorithm support the new joint mimic :
    - RNEA
    - CRBA
    - Forward Kinematics
    - Jacobians and Frames
    - Centroidal Algorithm

#### Testing & Validation:
- Added unit tests to validate mimic joint support for all the above algorithms.
- Verified URDF parsing for different robot models that include mimic joints.

## Limitations:
* Algorithms such as ABA, or any derivatives are not supported and should trigger asserts.
* Currently, the mimic joint should always be after the primary joint in the kinematic tree. (assert is triggered if not)

## Feedback Needed:
The naming of the new member variable and functions is pretty arbitrary, we are eager to change them to better suit pinocchio naming standards.
Non exhaustively, here are a list of the lesser quality one (that should most probably be renamed) : 
* `idx_j`/`nj` : representing the dimension and index in the "extended model"
* `jointCols`, `jointRows`, etc method has been split into `jointVelCols` and `jointJacCols` (respectively if they refer to `idx_v`/`nv` or `idx_j`/`nj`) 

## Special Thanks:
A special thank you to @EtienneAr for his guidance and advice throughout this development process.

2024-12-12 14:01 UTC, abussy-aldebaran commented
Hi,

I started using mimic joints, so I'm following this PR with interest !
I tested this branch with forward and inverse kinematics (with pseudo-inverses of the Jacobians), and it seems to work fine :+1: 

How/Where can I report any bug I find ?
I'll try to add MREs as unittests. For instance, I found : https://github.com/abussy-aldebaran/pinocchio/commit/5a8f2050b4785fa7ced21f513146461e09a15901

2024-12-12 15:13 UTC, abussy-aldebaran commented on include/pinocchio/multibody/model.hpp
Maybe you could add `typedef` for mimic joints ?
```c++
typedef JointModelMimicTpl<Scalar, Options, JointCollectionTpl> JointModelMimic;
typedef JointDataMimicTpl<Scalar, Options, JointCollectionTpl> JointDataMimic;
```

2024-12-13 07:34 UTC, abussy-aldebaran commented on include/pinocchio/parsers/urdf/model.hxx
> +        , axis(_axis)
I got a `-Wreorder` warning. `axis` should be first in the initialization list.

2024-12-13 09:03 UTC, abussy-aldebaran commented on include/pinocchio/multibody/joint/joint-mimic.hpp
> +      res.setIndexes(id(), idx_q(), idx_v(), idx_j());
Isn't a `setMimicIndices` missing ?
See https://github.com/abussy-aldebaran/pinocchio/commit/5a8f2050b4785fa7ced21f513146461e09a15901
and https://github.com/abussy-aldebaran/pinocchio/commit/afef317dbdb5721ba59042b3e9e78b2e0218c71b

2024-12-16 10:43 UTC, MegMll commented
> Hi,
> 
> I started using mimic joints, so I'm following this PR with interest ! I tested this branch with forward and inverse kinematics (with pseudo-inverses of the Jacobians), and it seems to work fine 👍
> 
> How/Where can I report any bug I find ? I'll try to add MREs as unittests. For instance, I found : [abussy-aldebaran@5a8f205](https://github.com/abussy-aldebaran/pinocchio/commit/5a8f2050b4785fa7ced21f513146461e09a15901)

Hi, 

Thanks a lot for your interest in this PR, ! In order to simplify the PR and the review process, if you want to add new unittests, please do it directly on this branch.

If you don't feel confortable with this solution, we'll find another way.

As for bugs, please add comments here, and we'll take a look at it. 

Thanks again !

2024-12-26 08:16 UTC, abussy-aldebaran commented
>In order to simplify the PR and the review process, if you want to add new unittests, please do it directly on this branch.

What do you mean ? Opening a PR in your forked repository ?

2025-01-14 16:40 UTC, jorisv requested changes

2025-01-14 16:40 UTC, jorisv commented on include/pinocchio/algorithm/kinematics.hpp
> +  SE3Tpl<Scalar, Options> getRelativePlacement(
Is this function still useful in this PR ? I don't see any use.

2025-01-14 16:40 UTC, jorisv commented on include/pinocchio/algorithm/model.hxx
> +      "index of primary is greater than the total of joints");
```suggestion
      "index_primary is greater than the total of joints");
```

2025-01-14 16:40 UTC, jorisv commented on include/pinocchio/algorithm/model.hxx
> +      "index of primary is greater than the total of joints");
```suggestion
      "index_secondary is greater than the total of joints");
```

2025-01-14 16:40 UTC, jorisv commented on include/pinocchio/algorithm/model.hxx
> +      index_primary < index_secondary, "index of primary is greater than secondary");
```suggestion
      index_primary < index_secondary, "primary_index must be lower than secondary_index");
```

2025-01-14 16:40 UTC, jorisv commented on include/pinocchio/algorithm/model.hxx
> +      input_model.joints.at(index_secondary), output_model.joints.at(index_primary), scaling,
```suggestion
      input_model.joints[index_secondary], output_model.joints[index_primary], scaling,
```
You already check index validity with PINOCCHIO_CHECK_INPUT_ARGUMENT.

2025-01-14 16:40 UTC, jorisv commented on include/pinocchio/algorithm/model.hxx
> +    int old_nv = input_model.joints.at(index_secondary).nv();
```suggestion
    int old_nq = input_model.joints[index_secondary].nq();
    int old_nv = input_model.joints[index_secondary].nv();
```

2025-01-14 16:40 UTC, jorisv commented on include/pinocchio/algorithm/model.hxx
> +          go.placement = static_cast<GeometryObject::SE3>(pframe.placement * pfMAB) * go.placement;
I build without this cast.

2025-01-14 16:40 UTC, jorisv commented on include/pinocchio/algorithm/model.hxx
> +        return res;
```suggestion
        return jmodel;
```

2025-01-14 16:40 UTC, jorisv commented on include/pinocchio/algorithm/model.hxx
> +          relative_placement = static_cast<SE3>(reduced_model.frames[reduced_frame_id].placement);
It build without this cast

2025-01-15 08:57 UTC, MegMll commented on include/pinocchio/algorithm/kinematics.hpp
> +  SE3Tpl<Scalar, Options> getRelativePlacement(
It was used in the first tries of the patches for rnea and crba algorithms. But now it's not used anymore, indeed.

2025-01-15 08:59 UTC, MegMll commented
> > In order to simplify the PR and the review process, if you want to add new unittests, please do it directly on this branch.
> 
> What do you mean ? Opening a PR in your forked repository ?

No directly push on this branch, so that the new unittests can be reviewed, here as well.

2025-01-15 11:48 UTC, jorisv requested changes

2025-01-15 11:48 UTC, jorisv commented on include/pinocchio/algorithm/jacobian.hxx
> +          for (int i = nj(model.joints[j]) - 1; i >= 0; i--)
Each `nj` call will call `boost::apply_visitor`.  Same for `idx_j` and `idx_v`.

The old algorithm was calling this visitor once, now we call it 3N time.
It's better to use the Algo::run pattern. At least, we will call the visitor only N time.

The only way to not call it at all is:
 - Store idx_j, idx_v and nj in JointModelTpl
 - Create a JacobianComputation structure that will store these values for each joint
 - Store in model a list of support J column for each joint

2025-01-15 11:48 UTC, jorisv commented on include/pinocchio/algorithm/jacobian.hxx
> +      const int colRefIn = nj(model.joints[joint_id]) + idx_j(model.joints[joint_id]) - 1;
Unused

2025-01-15 11:48 UTC, jorisv commented on include/pinocchio/algorithm/jacobian.hxx
> +          typename Pass::ArgsType(model, data, q.derived(), J_.const_cast_derived()));
```suggestion
          typename Pass::ArgsType(model, data, q.derived(), J_));
```

2025-01-15 11:48 UTC, jorisv commented on include/pinocchio/algorithm/jacobian.hxx
> +            const Eigen::DenseIndex col_out = idx_v(model.joints[j]) + i;
Same issue than for translateJacobian

2025-01-15 16:29 UTC, jorisv requested changes

2025-01-15 16:29 UTC, jorisv commented on include/pinocchio/algorithm/crba.hxx
> +          * model.joints.at(i).jointJacCols(data.J);
```suggestion
          * model.joints[i].jointJacCols(data.J);
```

2025-01-15 16:29 UTC, jorisv commented on include/pinocchio/algorithm/crba.hxx
> +        const JointIndex i = model.supports[primary_id].at(k);
```suggestion
        const JointIndex i = model.supports[primary_id][k];
```

2025-01-15 16:29 UTC, jorisv commented on include/pinocchio/algorithm/crba.hxx
> +          .noalias() -= model.joints.at(i).jointJacCols(data.J).transpose()
```suggestion
          .noalias() -= model.joints[i].jointJacCols(data.J).transpose()
```

2025-01-15 16:29 UTC, jorisv commented on include/pinocchio/algorithm/crba.hxx
> +      findCommonAncestor(model, primary_id, secondary_id, ancestor_prim, ancestor_sec);
Instead of computing this data at each call, it's maybe possible to store it in `JointDataMimicTpl`.

2025-01-15 16:29 UTC, jorisv commented on include/pinocchio/algorithm/crba.hxx
> +    static inline void mimic_patch_CrbaLocalConventionBackwardStep(
```suggestion
    static void mimic_patch_CrbaLocalConventionBackwardStep(
```

2025-01-15 16:29 UTC, jorisv commented on include/pinocchio/algorithm/crba.hxx
> +          model.supports[secondary_id].at(k + 1); // Child link to compute placement
```suggestion
        const JointIndex i = model.supports[secondary_id][k];
        const JointIndex ui =
          model.supports[secondary_id][k + 1]; // Child link to compute placement
```

2025-01-15 16:29 UTC, jorisv commented on include/pinocchio/algorithm/crba.hxx
> +        const JointIndex i = model.supports[primary_id].at(k);
```suggestion
        const JointIndex i = model.supports[primary_id][k];
```

2025-01-16 10:42 UTC, MegMll commented on include/pinocchio/algorithm/geometry.hxx
> +           * geom_model.geometryObjects[i].placement);
Did you try with CppAd ? I removed all the other cast, and ci with cppAd, does not work

2025-01-19 23:02 UTC, EtienneAr commented on include/pinocchio/algorithm/centroidal.hxx
> +        motionSet::inertiaAction<ADDTO>(data.oYcrb[i], J_cols, Ag_cols);
No, the default behavior is not changed

Before this backward pass, Ag is set to zero (line 177 of this file).
The columns of the DoF that does not involve any mimicking, are selected only once in this pass and thus "added to" only once. So for those Dof, the ADDTO act the same as a SETTO.

(But for the mimic DoF this allows for summing the results)

2025-01-20 14:13 UTC, EtienneAr commented on include/pinocchio/algorithm/crba.hxx
> +      findCommonAncestor(model, primary_id, secondary_id, ancestor_prim, ancestor_sec);
Yes, it would make sense.

The problem is that both JointModelMimic and JointDataMimic constructors are not "aware" of the full robot model, and don't have access to information on the kinematic tree at all...

2025-01-20 14:38 UTC, EtienneAr commented on include/pinocchio/algorithm/crba.hxx
> +      findCommonAncestor(model, primary_id, secondary_id, ancestor_prim, ancestor_sec);
I agree with you that computing every time seems like a waste, but I am not sure that it is worth storing it.

When `JointDataMimicTpl` is instantiated, it doesn't have any available information regarding the kinematic structure of the whole model. (The `JointModelMimicTpl` does not contain this information either)

2025-01-20 16:34 UTC, EtienneAr commented on include/pinocchio/parsers/urdf/model.hxx
> +        , axis(_axis)
Hello,
Thank you for the review.

This should have been solved by 0abc4f6fd62e0b69ad9cc135124bdb2128214f6e

2025-01-20 16:36 UTC, EtienneAr commented on include/pinocchio/algorithm/kinematics.hxx
> +      const JointIndex parent_id = std::min(jointIdRef, jointIdTarget);
Doing two backward passes is a very good idea. It has been done 8fdf846e3d6040f6c1943aec47b4708c83d5633c

2025-01-20 16:43 UTC, MegMll commented on include/pinocchio/algorithm/compute-all-terms.hxx
> +          && "Algorithm not supported for mimic joints");
All the asserts were changed to PINOCCHIO_THROW, so that it works in release mode (and in python)

2025-01-23 16:39 UTC, EtienneAr commented
Following our IRL meeting, here is the todo list:
- [ ] Refactor the `translateJacobian` to prevent performance drop (due to nested for loops and visitor call increase)
- [ ] Make sure the API (C++ & Python) is not broken by this PR (i.e. check that the non-mimic test did not change)
- [ ] Add a check "model has mimic" in robot model to factorize code, and use that check in algorithms
- [ ] Double check the necessity of the SE3 static_cast 
- [ ] Add specific check for mimic in check.hxx (instead of just skipping with an `if`).
- [ ] Revert all changes in unsupported algo
- [ ] Rename `nj`, `idx_j` -> `nv_extended`, `idx_v_extended`
- [ ] Make sure that jcalc is easily upgradable for non linear mimic (withoput API break)

The following point are Nice To Have and should be addressed in separate issues / PRs:
- [ ] Function to go from "Reduced" mimic model to full "extended" model
- [ ] Store extra data in robot model/data to speed up so algo
- [ ] Make proper safe/unsafe function for every algo to check (or not) input parameters, for performance issues and to be able to check for python bindings
- [ ] Function that give the constraint matrix from a "Reduced" mimic model

2025-01-27 16:40 UTC, jorisv requested changes

2025-01-27 16:40 UTC, jorisv commented on include/pinocchio/algorithm/default-check.hpp
> +    return makeAlgoCheckerList(ParentChecker(), CRBAChecker(), ABAChecker(), MimicChecker());
I don't think this should be added to the default checker list.
Default checker validate if the model is correct, Mimic doesn't imply the model is not valid, it only doesn't work on some algorithms…

2025-01-27 16:40 UTC, jorisv commented on include/pinocchio/multibody/data.hxx
> +                .nv();
First boost::get result can be stored.

2025-01-29 12:41 UTC, abussy-aldebaran commented
> No directly push on this branch, so that the new unittests can be reviewed, here as well.

Could you grant me the access rights to push, if that's still ok with you ?

2025-01-29 16:34 UTC, jorisv requested changes

2025-01-29 16:34 UTC, jorisv commented on include/pinocchio/multibody/joint/joint-translation.hpp
> +      data.joint_q = this->jointConfigExtendedModelSelector(qs);
Since this joint doesn't support mimic, we should use `jointConfigSelector`

2025-01-29 16:34 UTC, jorisv commented on include/pinocchio/multibody/joint/joint-common-operations.hpp
> +        && "No ConfigVectorAffineTransform specialized for this joint type");
I don't understand why there is these check.

2025-01-29 16:34 UTC, jorisv commented on include/pinocchio/multibody/joint/joint-free-flyer.hpp
> +    typedef boost::mpl::true_ is_mimicable_t;
It should be false ?

2025-01-29 16:34 UTC, jorisv commented on include/pinocchio/multibody/joint/joint-helical.hpp
ConfigVectorAffineTransform is not specialized, same for unaligned version.

2025-01-29 21:33 UTC, jorisv commented on include/pinocchio/multibody/joint/joint-basic-visitors.hpp
> +   *             the joint configuration space
```suggestion
   * @brief      Visit a JointModelTpl through JointNvExtendedVisitor to get the dimension of
   *             the joint extended tangent space
```

2025-01-29 21:34 UTC, jorisv commented on include/pinocchio/multibody/joint/joint-basic-visitors.hpp
> +   * tangent space corresponding to the first joint jacobian space degree
```suggestion
   * @brief      Visit a JointModelTpl through JointIdxVExtendedVisitor to get the index in the extended model
   * tangent space corresponding to the first joint jacobian space degree
```

2025-01-29 21:40 UTC, jorisv requested changes

2025-01-29 21:40 UTC, jorisv commented on include/pinocchio/multibody/joint/joint-basic-visitors.hpp
> +   * @return     The index in the full model tangent space corresponding to the first
```suggestion
   * @return     The index in the extended model tangent space corresponding to the first
```

2025-01-29 21:40 UTC, jorisv commented on include/pinocchio/multibody/joint/joint-basic-visitors.hpp
> +   * @return     The dimension of joint jacobian space
```suggestion
   * @return     The dimension of joint extended tangent space
```

2025-01-29 21:40 UTC, jorisv commented on include/pinocchio/multibody/joint/joint-basic-visitors.hpp
> +    int vExtended);
To preserve API, you must provide the old API

2025-01-29 21:40 UTC, jorisv commented on include/pinocchio/multibody/joint/joint-basic-visitors.hpp
> +   * @param[in]  vExtended       The index in the full model tangent space corresponding to the
```suggestion
   * @param[in]  vExtended       The index in the extended model tangent space corresponding to the
```

2025-01-30 10:55 UTC, jorisv requested changes

2025-01-30 10:55 UTC, jorisv commented on include/pinocchio/multibody/joint/joint-mimic.hpp
> +#include <iostream>
```suggestion
```

2025-01-30 10:55 UTC, jorisv commented on include/pinocchio/multibody/joint/joint-mimic.hpp
> +    , m_constraint(0)
```suggestion
    : m_constraint(0)
    , m_scaling_factor(scaling_factor)
```

2025-01-30 10:55 UTC, jorisv commented on include/pinocchio/multibody/joint/joint-mimic.hpp
> +      return M_;
Si on redéfinie TransformTypeConstRef pour qu'il devienne une valeur, alors on a peut-être pas besoin de copier la valeur dans un mutable.

2025-01-30 11:00 UTC, jorisv commented
>     * [x]  Make sure that jcalc is easily upgradable for non linear mimic (withoput API break)

We can add a functor to JointModelMimicTpl constructor argument. This functor will hold the functon to apply to the config and velocity vectors.

This can be added latter as:
- a new JointModelMimicTpl template argument set with a default value
- a std::function stored in JointModelMimicTpl

The latter options is less effective.
In both case, this will avoid a call to a visitor, since the configVectorAffineTransform can be solved at the JointModelMimmicTpl construction.

2025-01-30 13:00 UTC, jorisv commented on include/pinocchio/multibody/joint/joint-mimic.hpp
> +#include <iostream>
```suggestion
```

2025-01-30 16:17 UTC, jorisv requested changes

2025-01-31 08:41 UTC, EtienneAr commented on include/pinocchio/multibody/joint/joint-common-operations.hpp
> +        && "No ConfigVectorAffineTransform specialized for this joint type");
For joint where it is not trivial to define an affine transformation of the configuration, we still allow mimicking only if $\alpha = 1, \beta = 0$ (the identity transform: $q_{mimicked} = q_{mimicking}$)

2025-01-31 08:43 UTC, EtienneAr commented on include/pinocchio/multibody/joint/joint-free-flyer.hpp
> +    typedef boost::mpl::true_ is_mimicable_t;
With the above comment, if no transform is specified, the joint can still be a mimic if $\alpha = 1, \beta = 0$. Thus we allow the freeflyer to be mimicked under this condition.

2025-01-31 09:21 UTC, jorisv commented on include/pinocchio/multibody/model.hpp
Why ? There is no joint typedef in model.hpp

2025-01-31 09:35 UTC, jorisv commented on include/pinocchio/multibody/data.hxx
> +                .nv();
utiliser nvExtended()

2025-01-31 09:42 UTC, jorisv commented on include/pinocchio/multibody/joint/joint-common-operations.hpp
> +        && "No ConfigVectorAffineTransform specialized for this joint type");
After discussion we must set an assert

2025-01-31 16:15 UTC, jorisv requested changes

2025-01-31 16:15 UTC, jorisv commented on examples/collision-with-point-clouds.py
> +    urdf_model_path, package_dirs=mesh_dir
package_dirs is still de second argument, why specify it ?

2025-01-31 16:15 UTC, jorisv commented on examples/collisions.py
> +model = pin.buildModelFromUrdf(urdf_model_path, pin.JointModelFreeFlyer(), False)
False is the default argument, so we should no specify it (less diff)

2025-01-31 16:15 UTC, jorisv commented on examples/geometry-models.py
> +    urdf_model_path, mesh_dir, mimic=False
We should not specify it (less change)

2025-01-31 16:23 UTC, jorisv requested changes

2025-01-31 16:23 UTC, jorisv commented on unittest/liegroups.cpp
Revert change when setIndexes is back compatible

2025-01-31 16:23 UTC, jorisv commented on unittest/joint-prismatic.cpp
Revert change when setIndexes is back compatible

2025-01-31 16:23 UTC, jorisv commented on unittest/joint-generic.cpp
Revert some changes when setIndexes is back compatible

2025-01-31 16:23 UTC, jorisv commented on unittest/finite-differences.cpp
Revert setIndexes changes when setIndexes is back compatible

2025-01-31 16:23 UTC, jorisv commented on unittest/cppad/joints.cpp
Revert setIndexes changes when setIndexes is back compatible

2025-01-31 16:23 UTC, jorisv commented on unittest/all-joints.cpp
Revert setIndexes changes when setIndexes is back compatible

2025-01-31 16:23 UTC, jorisv commented on unittest/python/bindings_build_geom_from_urdf_memorycheck.py
Remove False when python API break is over

2025-01-31 16:23 UTC, jorisv commented on unittest/python/bindings_contact_inverse_dynamics.py
Remove False when python API break is over

2025-01-31 16:23 UTC, jorisv commented on unittest/reachable-workspace.cpp
> +  pinocchio::buildModels::manipulator(model, true);
I'm not sure we should activate mimic here. Reachable workspace use integration that should already be tested.

2025-02-03 08:56 UTC, MegMll commented on include/pinocchio/multibody/joint/joint-model-base.hpp
>      }
Should we also provide the 2 visitors to go with it ?

2025-02-03 14:47 UTC, MegMll commented on bindings/python/parsers/urdf/model.cpp
> +    Model buildModelFromUrdf(const bp::object & filename, const bool mimic = false)
So we do two functions ?

2025-02-07 16:36 UTC, jorisv requested changes

2025-02-07 16:36 UTC, jorisv commented on include/pinocchio/algorithm/rnea.hxx
> +        jmodel.jointVelocityExtendedModelSelector(data.tau) += jdata.S().transpose() * data.f[i];
Add a comment to explain the += allow to manage mimic joint (the quantity added to mimicked joint)

2025-02-07 16:36 UTC, jorisv commented on include/pinocchio/algorithm/rnea.hxx
> +      data.tau.setZero();
setZero because of mimic joint

2025-02-07 16:36 UTC, jorisv commented on include/pinocchio/algorithm/rnea.hxx
> +      data.tau.setZero();
setZero because of mimic joint

2025-02-07 16:36 UTC, jorisv commented on include/pinocchio/algorithm/rnea.hxx
> +        jmodel.jointVelocityExtendedModelSelector(data.nle) += jdata.S().transpose() * data.f[i];
Add a comment to explain the += allow to manage mimic joint (the quantity added to mimicked joint)

2025-02-07 16:36 UTC, jorisv commented on include/pinocchio/algorithm/rnea.hxx
> +      data.nle.setZero();
setZero because of mimic joint

2025-02-07 16:36 UTC, jorisv commented on include/pinocchio/algorithm/rnea.hxx
> +      data.g.setZero();
setZero because of mimic joint

2025-02-07 16:36 UTC, jorisv commented on include/pinocchio/algorithm/rnea.hxx
> +      data.g.setZero();
setZero because of mimic joint

2025-02-07 16:36 UTC, jorisv commented on include/pinocchio/algorithm/rnea.hxx
> +      data.tau.setZero();
setZero because of mimic joint

2025-02-07 16:36 UTC, jorisv commented on include/pinocchio/algorithm/rnea.hxx
> +        jmodel.jointVelocityExtendedModelSelector(g) += jdata.S().transpose() * data.f[i];
Add a comment to explain the += allow to manage mimic joint (the quantity added to mimicked joint)

2025-02-10 16:33 UTC, jorisv requested changes

2025-02-10 16:33 UTC, jorisv commented on bindings/python/algorithm/expose-model.cpp
> +    ModelTpl<Scalar, Options, JointCollectionTpl> transformJointIntoMimic(
You can use the same pattern as findCommonAncestor_proxy, this avoid to specify the full signature in the definition.

2025-02-10 16:33 UTC, jorisv commented on bindings/python/algorithm/expose-model.cpp
> +          const Model &, const JointIndex &, const JointIndex &, const double &, const double &))(
Use transformJointIntoMimic_proxy to note specify the full signature

2025-02-10 16:33 UTC, jorisv commented on bindings/python/parsers/urdf/model.cpp
> +        (bp::arg("urdf_filename"), bp::arg("root"), bp::arg("mimic") = false),
```suggestion
        (bp::arg("urdf_filename"), bp::arg("root_joint"), bp::arg("mimic") = false),
```

2025-02-10 16:33 UTC, jorisv commented on include/pinocchio/multibody/joint/joint-basic-visitors.hxx
> +  struct jointConfigExtendedModelSelectorVisitor
jointConfigExtendedModelSelectorVisitor => JointConfigExtendedModelSelectorVisitor

2025-02-10 16:33 UTC, jorisv commented on include/pinocchio/parsers/urdf.hpp
> +      const bool mimic = false,
Saddly, this also break the API. Call that set verbose to true will set mimic to true now…

We need to put mimic after verbose.

2025-02-11 15:15 UTC, MegMll commented on unittest/casadi/joints.cpp
> +  test(const pinocchio::JointModelMimicTpl<Scalar, Options, JointCollection> & /*jmodel*/)
We did the same test as for joint composite

2025-02-11 15:16 UTC, MegMll commented on bindings/python/algorithm/expose-model.cpp
> +      const ModelTpl<Scalar, Options, JointCollectionTpl> & input_model,
transform mimic cannot take context, because it's not cppad compatible

2025-02-11 15:21 UTC, jorisv commented on unittest/joint-composite.cpp
Ok

2025-02-11 15:22 UTC, jorisv commented on bindings/python/algorithm/expose-model.cpp
> +      const ModelTpl<Scalar, Options, JointCollectionTpl> & input_model,
Because of some equality tests ?

2025-02-11 15:28 UTC, MegMll commented on bindings/python/algorithm/expose-model.cpp
> +      const ModelTpl<Scalar, Options, JointCollectionTpl> & input_model,
I did not have time to investigate, it just won't compile, and since it's in a file with the PINOCCHIO_SKIP_ALGORITHM define, i just thought it made sense to use double. 

If we want it with casadi and autodiff, i can add it to the todo list

2025-02-12 08:07 UTC, MegMll commented on unittest/sample-models.cpp
> +BOOST_AUTO_TEST_CASE(compare_mimic)
We can remove it

2025-02-12 08:10 UTC, MegMll commented on unittest/kinematics.cpp
okay, i added it to the todo list

2025-02-12 15:30 UTC, jorisv commented on include/pinocchio/multibody/data.hpp
> +    std::vector<int> idx_v_extended_fromRow;
idx_vExtended_to_idx_v_fromRow

2025-02-14 13:46 UTC, Luigip98 commented
@MegMll Hi, I was trying to clone your branch but this error occurs:

pinocchio/include/pinocchio/algorithm/crba.hxx:423:33: error: ‘const struct pinocchio::ModelTpl<double, 0>’ has no member named ‘mimic_joints’; did you mean ‘mimicked_joints’?
  423 |       for (int i = 0; i < model.mimic_joints.size(); i++)
      |                           ~~~~~~^~~~~~~~~~~~
      |                           mimicked_joints
    
But mimiched_joints is not declared as well. Do you know why?

2025-02-14 14:08 UTC, MegMll commented
> @MegMll Hi, I was trying to clone your branch but this error occurs:
> 
> pinocchio/include/pinocchio/algorithm/crba.hxx:423:33: error: ‘const struct pinocchio::ModelTpl<double, 0>’ has no member named ‘mimic_joints’; did you mean ‘mimicked_joints’? 423 | for (int i = 0; i < model.mimic_joints.size(); i++) | ~~~~~~^~~~~~~~~~~~ | mimicked_joints
> 
> But mimiched_joints is not declared as well. Do you know why?

Sorry, changes are occuring, we did not check every algorithms. You can rename it mimcking_joints or wait it's going to change during the afternoon

2025-02-18 14:19 UTC, jorisv requested changes

2025-02-18 14:19 UTC, jorisv commented on include/pinocchio/algorithm/crba.hxx
> +          data.oYcrb[secondary_id], J_cols, jmodel.jointCols(data.Ag));
The comment didn't help. Why are we doing that ?

Suggestion:
> Fix data.oYcrb value by adding mimicking joint effect

2025-02-18 14:19 UTC, jorisv commented on include/pinocchio/algorithm/crba.hxx
> +        /* M[i,SUBTREE] = S'*F[1:6,SUBTR  EE] */
```suggestion
        /* M[i,SUBTREE] = S'*F[1:6,SUBTREE] */
```

2025-02-18 14:19 UTC, jorisv commented on include/pinocchio/algorithm/crba.hxx
> +          forceSet::se3Action<ADDTO>(data.liMi[i], iF, jF);
ADDTO is not mandatory if we use mimic_subtree_joint.

2025-02-18 14:19 UTC, jorisv commented on include/pinocchio/algorithm/crba.hxx
> +        JointIndex sub_mimic_id = data.mimic_subtree_joint[mims_id];
sub_mimic_id can get the 0 value. In this case, we should note use it.

2025-02-18 14:19 UTC, jorisv commented on include/pinocchio/algorithm/crba.hxx
> +      data.M.setZero();
Is it still mandatory ?

2025-02-18 14:34 UTC, MegMll commented on include/pinocchio/algorithm/crba.hxx
> +              data.J.middleCols(sup_idx_vExtended, sup_nvExtended).transpose() * Ag_sec;
I guess, we can, but i'm not sure to see what it will bring us. Could you explain a bit more, please ?

2025-02-18 14:43 UTC, MegMll commented on include/pinocchio/algorithm/crba.hxx
> +          forceSet::se3Action<ADDTO>(data.liMi[i], iF, jF);
it's a bit painful to get it, because we are in a loop on model.joints and therefore have no idea about what is the index of current joint mimic in the mimicking_joint list. 

If we want to do this, we need to transform the model.mimicking_joint, into a map, i guess

2025-02-18 15:08 UTC, MegMll commented on include/pinocchio/algorithm/crba.hxx
> +          data.oYcrb[secondary_id], J_cols, jmodel.jointCols(data.Ag));
I changed this line, to be more explicit.
The change also avoid computing twice the same matrix and also added a comment

2025-02-19 16:12 UTC, jorisv commented on include/pinocchio/algorithm/crba.hxx
> +          forceSet::se3Action<ADDTO>(data.liMi[i], iF, jF);
Ok, just comment the ADDTO could be avoided by using the data.mimic_subtree_joint. With the map search, we will not win so much time compared to adding the whole Fcrb matrix.

2025-02-19 16:34 UTC, jorisv requested changes

2025-02-19 16:34 UTC, jorisv commented on include/pinocchio/algorithm/jacobian.hxx
> +        // mimicked joint (since mimicked_id < mimicking_id) Do another pass to accumulate it back
```suggestion
        // Add mimicking joint effect into mimicked column
```

2025-02-19 16:34 UTC, jorisv commented on include/pinocchio/algorithm/jacobian.hxx
> +        // mimicked joint (since mimicked_id < mimicking_id) Do another pass to accumulate it back
```suggestion
        // Add mimicking joint effect into mimicked column
```

2025-02-20 10:35 UTC, jorisv requested changes

2025-02-20 10:35 UTC, jorisv commented on unittest/model.cpp
We should patch standard test to check idx_vExtendeds, nvExtendeds, mimicking_joints and mimicked_joints.

2025-02-24 13:05 UTC, MegMll commented on unittest/model.cpp
Add tests to make sure mimicked and mimicking are sorted in joints order

2025-02-25 10:43 UTC, jorisv requested changes

2025-02-25 10:43 UTC, jorisv commented on include/pinocchio/bindings/python/utils/model-checker.hpp
> +        "This algorithm does not support Joint Mimic type in the model.";
```suggestion
      static const std::string m_error_message =
        "This algorithm does not support Joint Mimic type in the model.";
```

2025-02-25 10:43 UTC, jorisv commented on include/pinocchio/bindings/python/utils/model-checker.hpp
Add this file to sources.cmake (around line 496)

2025-02-27 09:14 UTC, jorisv commented on include/pinocchio/multibody/liegroup/liegroup-algo.hxx
> +        jmodel.jointExtendedModelBlock(PINOCCHIO_EIGEN_CONST_CAST(JacobianMatrixType, mat)), arg,
To revert

2025-02-27 09:16 UTC, jorisv commented on unittest/model.cpp
check that mimicking_joints and mimicked_joints are sorted

2025-02-27 09:28 UTC, jorisv commented on CHANGELOG.md
> +  - `JointMapped{Config,Velocity}Selector` to get mimicked joint configuration/velocity from the mimicking joint
add line for:
- buildMimicModel
- Model new members
- Data new members
- Change in GeometryModel Scalar value : https://github.com/stack-of-tasks/pinocchio/issues/2445

2025-02-27 16:34 UTC, jorisv approved these changes

2025-02-28 09:05 UTC, merged